services:
  - type: web
    name: kennedia-tracker
    env: node
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_NAME
        sync: false
